=== ctperry0301/csc366Deliverable3/DTDS/Location.dtd
<!DOCTYPE location [
<!ELEMENT location (address, city, country, owner+, locationManager+, receipts, inventory)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT owner (name, startDate, endDate)>
<!ELEMENT locationManager (employeeId, startDate, endDate)>
<!ELEMENT receipts (receipt*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT startDate (#PCDATA)>
<!ELEMENT endDate (#PCDATA)>
<!ELEMENT employeeId (#PCDATA)>
<!ELEMENT receipt (date, customerId, purchasedItem+)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT customerId (#PCDATA)>
<!ELEMENT purchasedItem (#PCDATA)>
<!ELEMENT inventory (packagedGoods, ingredients)>
<!ELEMENT packagedGoods (good*)>
<!ELEMENT good (name)>
<!ELEMENT ingredients (ingredient)>
<!ELEMENT ingredient (name)>
<!ATTLIST location
  id ID #REQUIRED
  dateOpened #PCDATA #REQUIRED
>
<!ATTLIST good
  quantity #PCDATA #REQUIRED
  currentPrice #PCDATA #REQUIRED
>
<!ATTLIST ingredient
  quantity #PCDATA #REQUIRED
  currentPrice #PCDATA #REQUIRED
>
]>

=== ctperry0301/csc366Deliverable3/XML/location.xml
<?xml version="1.0"?>
<!DOCTYPE location SYSTEM "location.dtd">
<location id=1 dateOpened="02/19/1999">
    <address>39204 Street</address>
    <city>San Luis Obispo</city>
    <country>United States</country>
    <owner>
        <name>John Smith</name>
        <startDate>12/24/2000</startDate>
        <endDate>12/24/2000</endDate>
    </owner>
    <locationManager>
        <employeeId>1</employeeId>
        <startDate>02/04/2018</startDate>
        <endDate>12/24/2000</endDate>
    </locationManager>
    <receipts>
        <receipt>
           <date>02/04/2022</date>
            <customerId>2</customerId>
            <purchasedItem>apple</purchasedItem>
              <purchasedItem>crackers</purchasedItem>
        </receipt>
        <receipt>
            <date>02/04/2022</date>
            <customerId>1</customerId>
            <purchasedItem>apple</purchasedItem>
        </receipt>
    </receipts>
    <inventory>
        <packagedGoods>
            <good quantity=5 currentPrice=10.00>
                <name>crackers</name>
            </good>
            <good quantity=5 currentPrice=10.00>
                <name>crackers</name>
            </good>
        </packagedGoods>
        <ingredients>
            <ingredient quantity=5 currentPrice=10.00>
                <name>apple</name>
            </ingredient>
            <ingredient quantity=5 currentPrice=10.00>
                <name>orange</name>
            </ingredient>
            <ingredient quantity=5 currentPrice=10.00>
                <name>banana</name>
            </ingredient>
        </ingredients>
    </inventory>
</location>
